kind: Template
apiVersion: v1
metadata:
  name: blast-text-template
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-python
labels:
  template: blast-text-template
objects:
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: text
      labels:
        name: text
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_SECRET}"
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast.git
        contextDir: text
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: text:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: text
  #
  # deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: text
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - text
            from:
              kind: ImageStreamTag
              name: text:latest
        - type: ConfigChange
      replicas: 1
      selector:
        name: text
      template:
        metadata:
          labels:
            name: text
        spec:
          containers:
            - name: text
              image: text
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /blast/api/v1.0/text/x
                  port: 8080
                  scheme: HTTP
              env:
                - name: MONGODB_USER
                  value: "${MONGODB_USER}"
                - name: MONGODB_PASSWORD
                  value: "${MONGODB_PASSWORD}"
                - name: APP_MODULE
                  value: api:app
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: text
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: text
  #
  # route configuration
  #
  - kind: Route
    apiVersion: v1
    metadata:
      name: text
    spec:
      to:
        kind: Service
        name: text
  #
  # backend deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: text-db
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        name: text-db
      template:
        metadata:
          labels:
            name: text-db
        spec:
          containers:
            - name: text-db
              image: centos/mongodb-32-centos7:latest
              ports:
                - containerPort: 27017
                  protocol: TCP
              env:
                - name: MONGODB_USER
                  value: "${MONGODB_USER}"
                - name: MONGODB_PASSWORD
                  value: "${MONGODB_PASSWORD}"
                - name: MONGODB_DATABASE
                  value: blast_text
                - name: MONGODB_ADMIN_PASSWORD
                  value: "${MONGODB_ADMIN_PASSWORD}"
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # backend service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: text-db
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 27017
          targetPort: 27017
      selector:
        name: text-db
#
# template parameters generation configuration
#
parameters:
  - name: GITUB_SECRET
    description: github webhook secret
    generate: expression
    from: "[A-Z0-9]{16}"
    required: true
  - name: GENERIC_SECRET
    description: generic webhook secret
    generate: expression
    from: "[A-Z0-9]{16}"
    required: true
  - name: MONGODB_USER
    description: mongodb database username
    generate: expression
    from: "user[A-Z0-9]{4}"
    required: true
  - name: MONGODB_PASSWORD
    description: mongodb database password
    generate: expression
    from: "[A-Z0-9]{9}"
    required: true
  - name: MONGODB_ADMIN_PASSWORD
    description: mongodb database admin password
    generate: expression
    from: "[A-Z0-9]{9}"
    required: true
