kind: Template
apiVersion: v1
metadata:
  name: openshift-microservices
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-python
labels:
  template: openshift-microservices-template
objects:
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: blast-image
      labels:
        name: blast-image
    spec:
      triggers:
        - type: GitHub
          github:
            secret: secret101
        - type: Generic
          generic:
            secret: secret101
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast.git
        contextDir: image
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: blast-image:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: blast-image
  #
  # deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: blast-image
    spec:
      strategy:
        type: Rolling
        rollingParams:
          pre:
            failurePolicy: Abort
            execNewPod:
              containerName: blast-image
              command:
              - container-entrypoint
              - python
              - initdb.py
              env:
                - name: POSTGRESQL_USER
                  value: "${POSTGRESQL_USER}"
                - name: POSTGRESQL_PASSWORD
                  value: "${POSTGRESQL_PASSWORD}"
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - blast-image
            from:
              kind: ImageStreamTag
              name: blast-image:latest
        - type: ConfigChange
      replicas: 1
      selector:
        name: blast-image
      template:
        metadata:
          labels:
            name: blast-image
        spec:
          containers:
            - name: blast-image
              image: blast-image
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /blast/api/v1.0/image/x
                  port: 8080
                  scheme: HTTP
              env:
                - name: POSTGRESQL_USER
                  value: "${POSTGRESQL_USER}"
                - name: POSTGRESQL_PASSWORD
                  value: "${POSTGRESQL_PASSWORD}"
                - name: APP_MODULE
                  value: api:app
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: blast-image
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: blast-image
  #
  # route configuration
  #
  - kind: Route
    apiVersion: v1
    metadata:
      name: blast-image
    spec:
      to:
        kind: Service
        name: blast-image
  #
  # backend deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: blast-image-db
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        name: blast-image-db
      template:
        metadata:
          labels:
            name: blast-image-db
        spec:
          containers:
            - name: blast-image-db
              image: openshift/postgresql-92-centos7:latest
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_USER
                  value: "${POSTGRESQL_USER}"
                - name: POSTGRESQL_PASSWORD
                  value: "${POSTGRESQL_PASSWORD}"
                - name: POSTGRESQL_DATABASE
                  value: blast_image
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # backend service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: blast-image-db
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        name: blast-image-db
#
# template parameters generation configuration
#
parameters:
  - name: POSTGRESQL_USER
    description: postgresql database username
    generate: expression
    from: "user[A-Z0-9]{4}"
    required: true
  - name: POSTGRESQL_PASSWORD
    description: posgresql database password
    generate: expression
    from: "[A-Z0-9]{9}"
    required: true
